# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: diesel_demo
    ports:
      - "5432:5432"